
<?php
if($this->session->get('AUTH_ROLE')=='guru'){
    echo $this->tag->linkTo(["/kelas/addClass", "Buat Kelas Baru", 'class' => 'btn btn-success']);
}
// var_dump($result);
if ($result->count() > 0) {
?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            
                <br>
                <!-- <td colspan="12">Results quantity: <?php echo $result->count(); ?></td> -->
                
                
                <br>
                <br>
            <tr>
                <th>Mata Pelajaran</th>

                <th>Pengajar</th>
                <th>Ruang</th>
                <th>Waktu</th>
                <th></th>

            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="13">Results quantity: <?php echo $result->count(); ?></td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach ($result as $data) { ?>
                <tr>
                    <td><?php echo $data->mapel; ?></td>

                    <td><?php echo $data->pengajar; ?></td>
                    <td><?php echo $data->ruang; ?></td>
                    <td><?php echo $data->waktu; ?></td>
                    <td><?php if($this->session->get('AUTH_ROLE')=='guru'){
                        echo $this->tag->linkTo(["kelas/edit/$data->id", '<i class="fa fa-sign-out" aria-hidden="true"></i> Edit Kelas', "class" => "btn btn-primary"]);
                        echo $this->tag->linkTo(["kelas/delete/$data->id", '<i class="fa fa-sign-out" aria-hidden="true"></i> Hapus Kelas', "class" => "btn btn-danger"]); 
                    }
                    else {
                       echo $this->tag->linkTo(["user/unenroll/$data->kelas_id", '<i class="fa fa-sign-out" aria-hidden="true"></i> Batal Ambil', "class" => "btn btn-danger"]);} ?></td>

                </tr>
            <?php } ?>
        </tbody>
    </table>
    
<?php
}
else{
?>
    <h2 align="center">Tidak Ada Kelas</h2>
    <?php
}
echo $this->tag->linkTo(["/user/profile", "Back", 'class' => 'btn btn-danger']);