
<!DOCTYPE html>
<html>


<div class="jumbotron bg-light" >
        <h1 align="center">BIMBIM</h1>
        <p align="center">Website Bimbel Manajer</p>
    </div>

<div >
        <h4 align="center">Atur jadwal kegiatan Bimbel anda dengan lebih mudah</h4>
       
    </div>

<br><br><br>

<?php
    if($this->session->has('AUTH_ID')){
        echo $this->tag->linkTo(["/user/profile", "Kelola Kelas", 'class' => 'btn btn-primary ']);
    }


