<div class="container">
    <!-- <div class> -->
    <h2>User Profile</h2>
    <hr>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Hello, <?= $this->session->get('AUTH_NAME') ?></h5>
            <p class="card-text"><?= $this->session->get('AUTH_ID') ?></p>
            <p class="card-text"><small class="text-muted">Created at <?=  date('d-m-Y H:m:s', $this->session->get('AUTH_CREATED')) ?></small></p>
            <?= $this->tag->linkTo(["kelas", '<i class="fa fa-sign-out" aria-hidden="true"></i> Semua Kelas', "class" => "btn btn-success"]); ?>
            <?= $this->tag->linkTo(["kelas/user", '<i class="fa fa-sign-out" aria-hidden="true"></i> Kelas Saya', "class" => "btn btn-success"]); ?>
        </div>
    </div>
</div>