<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/png" href="<?php echo $this->url->get('img/img-bimbim.png')?>"/>
    </head>
    <body>
    <nav class="navbar navbar-expand-md bg-info navbar-dark sticky-top">
            <a class="navbar-brand" href="/">BIMBIM</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navb" class="navbar-collapse collapse hide">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="/user/profile">Tim</a>
                    </li> -->
                </ul>

                <ul class="nav navbar-nav ml-auto">
                <?php
                    if ($this->session->has('AUTH_ID')){
                        echo"<li class=\"nav-item\">";
                        echo $this->tag->linkTo([
                            "/user/profile",
                            '<span class="fas fa-user"></span> Profile',
                            "class" => "nav-link"
                        ]);
                        
                        echo"</li>";
                        echo $this->tag->linkTo([
                            "user/logout",
                            '<span class="fas fa-sign-out"></span> Keluar',
                            "class" => "nav-link"
                        ]);
                        echo"</li>";
                    } else{
                        // echo"<li class=\"nav-item\">";
                        // echo $this->tag->linkTo([
                        //     "user/register",
                        //     '<span class="fas fa-user"></span> Daftar',
                        //     "class" => "nav-link"
                        // ]);
                        echo"</li>";
                        echo"<li class=\"nav-item\">";
                        echo $this->tag->linkTo([
                            "user/login",
                            '<span class="fas fa-sign-in-alt"></span> Masuk',
                            "class" => "nav-link"
                        ]);
                        echo"</li>";
                    } ?>
                </ul>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>
